### ISSUE TITLE
Add Affine to homebrew ?

### ISSUE THREAD

**Issue by stuaxo** [rasterio/affine#100]
I had a quick look and on ubuntu there is `python3-affine`, and at least on rpm distros there is a package of the same name, so things are looking pretty good for linux outside of pip (which is pretty big for beginners).

On the mac side I couldn't find Affine on homebrew, would it be possible to add a formula for it there ?

https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by sgillies** [comment]
@stuaxo I don't use homebrew, so I'm not personally motivated to do this, but I wouldn't mind if you maintained a formula and added some supporting files to this repo.
